services:
  arr-calendar:
    build: .                        # builds from the local Dockerfile
    #image: ghcr.io/mrainone7p/media-preview:latest  # uncomment once pushed to GHCR
    container_name: arr-calendar
    environment:
      TZ: "America/New_York"        # your timezone
    ports:
      - "8096:80"                   # change 8096 to any free port
    restart: unless-stopped
