services:
  arr-calendar:
    image: ghcr.io/mrainone7p/media-preview:latest
    #build: .                        # uncomment to build locally instead
    container_name: arr-calendar
    environment:
      TZ: "America/New_York"        # your timezone
    ports:
      - "8096:80"                   # change 8096 to any free port
    restart: unless-stopped
